import streamlit as st
from streamlit_webrtc import webrtc_streamer

# page header section
st.header("""E.S.R.A (Enhanced Sensory Recognition w/ AI)""", divider='rainbow')

# header caption section
st.caption("""This demonstration aims to showcase the utility of computer vision as a means of instantaneously demonstrating OFS-X software by
removing the hurdles of Puppy installation and connectivity and providing access to richer data contexts. """)

# how to use section
st.markdown("### How to Use")
st.text("""1. Point your devices camera to the manufacturing line you want to begin counting.
2. Whenever you're ready, hit the start button to begin the real-time video stream.
3. Take a look at the metrics generated by the computer vision model""")

# real-time video streaming section
webrtc_streamer(key="sample")

# metrics section
st.markdown("### Metrics")
col1, col2, col3 = st.columns([1,1,1]);

col1.metric(label="Objects Detected", value="25 Units")
col1.metric(label="Rate", value="1500 U/Hr")

col2.metric(label="Object Labels", value="Cups")
col2.metric(label="Latest Confidence", value="94.6%", delta="3.2%")

col3.metric(label="Resolution", value="828 x 1792")
col3.metric(label="Frames per Second", value="50 FPS", delta="-10 FPS")


